# Add binaries into the path
PATH=~/.dotfiles/bin:$PATH
PATH=/Users/Ygol/Library/Python/3.6/bin:$PATH
export PATH

# Source all files in ~/.dotfiles/source/
function src() {
  local file
  if [[ "$1" ]]; then
    source "$HOME/.dotfiles/source/$1.sh"
  else
    for file in ~/.dotfiles/source/*; do
      source "$file"
    done
  fi
}

# Run dotfiles script, then source.
function dotfiles() {
  ~/.dotfiles/bin/dotfiles "$@" && src
}

#src

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
alias vi="vim -u ~/.vimrc.mini"
export PS1="\\u@\h \\W]\\$"
alias fuck='sudo $(fc -ln -1)'
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export COMPOSE_IMPERSONATION='501:20'

# Setting for the new UTF-8 terminal support in Lion
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
