export PATH=~/.dotfiles/bin:$PATH
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/libs/oh-my-zsh
ZSH_CUSTOM=$HOME/.dotfiles/conf/zsh


# Set name of the theme to load.
DEFAULT_USER='Ygol'

#ZSH_THEME="pure"
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#ZSH_THEME="3den"
ZSH_THEME="cjt"
# ZSH_THEME="powerlevel9k/powerlevel9k"

# New conf from: https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#tritlos-configuration
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv vi_mode ip )
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

local user_symbol="$"
if [[ $(print -P "%#") =~ "#" ]]; then
  user_symbol = "#"
fi

POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="$user_symbol "
# POWERLEVEL9K_SHOW_CHANGESET=true
# POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

DISABLE_UPDATE_PROMPT="true"

KEYTIMEOUT=1

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(z brew cpanm docker git git-extras git-hubflow github gem bundler nvm osx postgres rake rails rbenv tmux ssh-agent tmuxinator vundle vi-mode copydir history web-search fastd virtualenv clipboard)

source $ZSH/oh-my-zsh.sh

#fpath=( "$HOME/.dotfiles/libs/pure-zsh" $fpath )
#autoload -U promptinit && promptinit
#prompt pure

# ssh agent config

zstyle :omz:plugins:ssh-agent agent-forwarding on

bindkey -v
bindkey -M vicmd "/" history-incremental-search-backward
bindkey '^R' history-incremental-search-backward
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^k' kill-line
bindkey -a u undo
bindkey -a '^R' redo
bindkey '^G' what-cursor-position





# Source all files in ~/.dotfiles/source/
function src() {
  local file
  if (( $# == 0 )); then
    for file in ~/.dotfiles/source/*; do
      source "$file"
    done
  else
    source "$HOME/.dotfiles/source/$1.sh"
  fi
}

# Run dotfiles script, then source.
function dotfiles() {
  ~/.dotfiles/bin/dotfiles "$@" && src
}

src

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

if [ "$TERM_PROGRAM" = "iTerm" ]; then
  test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
fi

if [ "$0" = "/usr/sbin/lightdm-session" -a "$DESKTOP_SESSION" = "i3" ]; then
    export $(gnome-keyring-daemon -s)
fi
#keychain id_rsa id_dsa
#. ~/.keychain/`uname -n`-sh

# Ygol ADDED
export PATH=~/bin:$PATH
# taken from https://www.codementor.io/linux/tutorial/configure-linux-toolset-zsh-tmux-vim
# want your terminal to support 256 color schemes? I do ...
export TERM="xterm-256color"

# Add this to your zshrc or bzshrc file
_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}

ensure_tmux_is_running

# my Aliases
if [ "$(uname 2> /dev/null)" = "Darwin"  ]; then
      alias vim='mvim -v'
fi
# convenience aliases for editing configs
alias ev='vim ~/.vimrc'
alias et='vim ~/.tmux.conf'
alias ez='vim ~/.zshrc'
alias org='vim ~/Dropbox/Org/ygol_mlo.org'

alias cl='clear'
compdef g=git
function g {
  if [[ $# -gt 0  ]]; then
        git "$@"
          else
                git status --short --branch
                  fi

}
